# File name: 3_kivi.py
<Widgets>:
    Button:
        size: 100, 100
        pos: 0, 0
        text: "Wojciech"
        color: 1, 1, 0, 1
        

    Button:
        size: 100, 100
        pos: 100, 0 # 0,0 is the left bottom corner!
        text: "Orzechowski"
        color: 1, 0, 0, 1 # RGB + transparency
        	

    Button:

        size: 200, 100
        pos: 200,0
        text: "Github.com/arcyfelix"
        color: 1, 0, 0, 1
        
